monitor = , preferred, auto, 1.2

exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprpaper
exec-once = mako
exec-once = kanshi

$mainMod = SUPER

input {
  kb_options = caps:swapescape
  repeat_rate = 50
  repeat_delay = 250

  touchpad {
    natural_scroll = true
    disable_while_typing = true
  }
}

master {
  mfact = 0.60
}

general {
  layout = master
}

# Window rules
windowrule = opacity 0.9,match:class foot

# General
bind = $mainMod SHIFT, E, exit,

# Launchers
bind = $mainMod SHIFT, Return, exec, foot
bind = $mainMod, SPACE, exec, pkill fuzzel || fuzzel
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy

# Window management
bind = $mainMod SHIFT, Q, killactive,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod SHIFT, F, fullscreen, 1
bind = $mainMod, V, togglefloating,
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod SHIFT, mouse:272, resizewindow
bind = $mainMod, Return, layoutmsg, swapwithmaster master
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev
bind = $mainMod SHIFT, J, layoutmsg, swapnext
bind = $mainMod SHIFT, K, layoutmsg, swapprev
bind = $mainMod, L, layoutmsg, mfact +0.02
bind = $mainMod, H, layoutmsg, mfact -0.02
bind = $mainMod, B, exec, pkill -USR1 waybar

# Workspace management
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bind = $mainMod, Tab, workspace, e+1
bind = $mainMod SHIFT, Tab, workspace, e-1
bind = $mainMod CTRL, Tab, movetoworkspace, e+1
bind = $mainMod CTRL SHIFT, Tab, movetoworkspace, e-1

# Monitor management
bind = $mainMod, W, focusmonitor, +1
bind = $mainMod SHIFT, W, movewindow, mon:+1


# Laptop keys
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86Launch6, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 10%-
